# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=9)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
