# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesettings',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
