# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_assist', '0002_savesettings_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesettings',
            name='activity',
            field=models.TextField(null=True),
        ),
    ]
