# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-13 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_assist', '0002_usersummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersummary',
            name='SummaryList',
            field=models.TextField(default='[]'),
        ),
    ]
