# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_assist', '0003_savesettings_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savesettings',
            name='volume',
        ),
        migrations.AddField(
            model_name='savesettings',
            name='blouetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savesettings',
            name='brightness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='savesettings',
            name='mobileData',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savesettings',
            name='vibrationMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savesettings',
            name='volumeLevel',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='savesettings',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
