# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_assist', '0011_savesettings_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savesettings',
            name='reminder',
        ),
    ]
