# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_assist', '0013_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder',
            new_name='reminder_title',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_text',
            field=models.TextField(null=True),
        ),
    ]
