# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_assist', '0014_auto_20161016_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_title',
            field=models.CharField(max_length=100),
        ),
    ]
